{{- if and .Values.worker.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dns-go.fullname" . }}-worker
  labels:
    {{- include "dns-go.worker.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "dns-go.worker.selectorLabels" . | nindent 6 }}
{{- end }}
