apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns-go

resources:
  - namespace.yaml
  - configmap.yaml
  - control-deployment.yaml
  - worker-deployment.yaml

commonLabels:
  app.kubernetes.io/name: dns-go
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: dns-go
    newName: ghcr.io/piwi3910/dns-go
    newTag: latest
